version: '3.8'

services:
  task-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
      - ./config:/quants-lab/config
      - ./outputs:/quants-lab/outputs
      - ./app/data:/quants-lab/app/data
    build: .
    env_file:
      - .env
    network_mode: host
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
