# Notifiers Configuration for QuantsLab

telegram:
  enabled: true
  bot_token: "${TELEGRAM_BOT_TOKEN}"  # Set in .env file
  chat_id: "${TELEGRAM_CHAT_ID}"      # Set in .env file
  # Optional settings
  parse_mode: "HTML"  # Can be "HTML", "Markdown", or null
  disable_notification: false
  
email:
  enabled: false
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "${EMAIL_USERNAME}"      # Set in .env file
  password: "${EMAIL_PASSWORD}"      # Set in .env file
  from_address: "${EMAIL_FROM}"      # Set in .env file
  to_addresses: ["${EMAIL_TO}"]      # Set in .env file
  
discord:
  enabled: false
  webhook_url: "${DISCORD_WEBHOOK_URL}"  # Set in .env file

slack:
  enabled: false
  webhook_url: "${SLACK_WEBHOOK_URL}"    # Set in .env file
  channel: "#general"